/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface LodCard {
        "address": string;
        "addressUrl": string;
        "articleTitle": string;
        "date": string;
        "description": string;
        "imageUrl": string;
        "readMoreText": string;
        "readMoreUrl": string;
        "tag": string;
    }
    interface LodCards {
        "countquery": string;
        "ctatext": string;
        "ctaurl": string;
        "endpoint": string;
        "itemsperpage": string;
        "query": string;
    }
    interface LodTable {
        "countquery": string;
        "ctatext": string;
        "ctaurl": string;
        "endpoint": string;
        "itemsperpage": string;
        "query": string;
    }
}
declare global {
    interface HTMLLodCardElement extends Components.LodCard, HTMLStencilElement {
    }
    var HTMLLodCardElement: {
        prototype: HTMLLodCardElement;
        new (): HTMLLodCardElement;
    };
    interface HTMLLodCardsElement extends Components.LodCards, HTMLStencilElement {
    }
    var HTMLLodCardsElement: {
        prototype: HTMLLodCardsElement;
        new (): HTMLLodCardsElement;
    };
    interface HTMLLodTableElement extends Components.LodTable, HTMLStencilElement {
    }
    var HTMLLodTableElement: {
        prototype: HTMLLodTableElement;
        new (): HTMLLodTableElement;
    };
    interface HTMLElementTagNameMap {
        "lod-card": HTMLLodCardElement;
        "lod-cards": HTMLLodCardsElement;
        "lod-table": HTMLLodTableElement;
    }
}
declare namespace LocalJSX {
    interface LodCard {
        "address"?: string;
        "addressUrl"?: string;
        "articleTitle"?: string;
        "date"?: string;
        "description"?: string;
        "imageUrl"?: string;
        "readMoreText"?: string;
        "readMoreUrl"?: string;
        "tag"?: string;
    }
    interface LodCards {
        "countquery"?: string;
        "ctatext"?: string;
        "ctaurl"?: string;
        "endpoint"?: string;
        "itemsperpage"?: string;
        "query"?: string;
    }
    interface LodTable {
        "countquery"?: string;
        "ctatext"?: string;
        "ctaurl"?: string;
        "endpoint"?: string;
        "itemsperpage"?: string;
        "query"?: string;
    }
    interface IntrinsicElements {
        "lod-card": LodCard;
        "lod-cards": LodCards;
        "lod-table": LodTable;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "lod-card": LocalJSX.LodCard & JSXBase.HTMLAttributes<HTMLLodCardElement>;
            "lod-cards": LocalJSX.LodCards & JSXBase.HTMLAttributes<HTMLLodCardsElement>;
            "lod-table": LocalJSX.LodTable & JSXBase.HTMLAttributes<HTMLLodTableElement>;
        }
    }
}
