/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface ArticlePreviewList {
        "countquery": string;
        "ctatext": string;
        "ctaurl": string;
        "endpoint": string;
        "itemsperpage": string;
        "query": string;
    }
    interface ArticlePreviewTable {
        "countquery": string;
        "ctatext": string;
        "ctaurl": string;
        "endpoint": string;
        "itemsperpage": string;
        "query": string;
    }
    interface LodCard {
        "address": string;
        "addressUrl": string;
        "articleTitle": string;
        "date": string;
        "description": string;
        "imageUrl": string;
        "readMoreText": string;
        "readMoreUrl": string;
        "tag": string;
    }
}
declare global {
    interface HTMLArticlePreviewListElement extends Components.ArticlePreviewList, HTMLStencilElement {
    }
    var HTMLArticlePreviewListElement: {
        prototype: HTMLArticlePreviewListElement;
        new (): HTMLArticlePreviewListElement;
    };
    interface HTMLArticlePreviewTableElement extends Components.ArticlePreviewTable, HTMLStencilElement {
    }
    var HTMLArticlePreviewTableElement: {
        prototype: HTMLArticlePreviewTableElement;
        new (): HTMLArticlePreviewTableElement;
    };
    interface HTMLLodCardElement extends Components.LodCard, HTMLStencilElement {
    }
    var HTMLLodCardElement: {
        prototype: HTMLLodCardElement;
        new (): HTMLLodCardElement;
    };
    interface HTMLElementTagNameMap {
        "article-preview-list": HTMLArticlePreviewListElement;
        "article-preview-table": HTMLArticlePreviewTableElement;
        "lod-card": HTMLLodCardElement;
    }
}
declare namespace LocalJSX {
    interface ArticlePreviewList {
        "countquery"?: string;
        "ctatext"?: string;
        "ctaurl"?: string;
        "endpoint"?: string;
        "itemsperpage"?: string;
        "query"?: string;
    }
    interface ArticlePreviewTable {
        "countquery"?: string;
        "ctatext"?: string;
        "ctaurl"?: string;
        "endpoint"?: string;
        "itemsperpage"?: string;
        "query"?: string;
    }
    interface LodCard {
        "address"?: string;
        "addressUrl"?: string;
        "articleTitle"?: string;
        "date"?: string;
        "description"?: string;
        "imageUrl"?: string;
        "readMoreText"?: string;
        "readMoreUrl"?: string;
        "tag"?: string;
    }
    interface IntrinsicElements {
        "article-preview-list": ArticlePreviewList;
        "article-preview-table": ArticlePreviewTable;
        "lod-card": LodCard;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "article-preview-list": LocalJSX.ArticlePreviewList & JSXBase.HTMLAttributes<HTMLArticlePreviewListElement>;
            "article-preview-table": LocalJSX.ArticlePreviewTable & JSXBase.HTMLAttributes<HTMLArticlePreviewTableElement>;
            "lod-card": LocalJSX.LodCard & JSXBase.HTMLAttributes<HTMLLodCardElement>;
        }
    }
}
