name: Deploy Stencil to GitHub Pages

on:
  push:
    branches:
      - main  # Replace with the branch you want to trigger the workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Setup Pages
        uses: actions/configure-pages@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Build Stencil.js project
        run: npm run build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          # Upload webcomponents directory
          path: 'www'
  
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
